image: mvdan/fdroid-ci:client-20160731

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  script:
    - export GRADLE_USER_HOME=$PWD/.gradle
    - ./gradlew assemble
    - ./gradlew test || {
          for log in app/build/reports/*ests/*/*ml; do
              echo "read $log here:";
              cat "$log" | curl --silent -F 'clbin=<-' https://clbin.com;
          done;
          exit 1;
      }
    # this file changes every time but should not be cached
    - rm -f $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
